### ISSUE TITLE
Back and Restart buttons inconsistent

### ISSUE THREAD

**Issue by ave-llan** [codefordc/expungement-dc#50]
The back and restart buttons don't always work.  On mobile, they rarely work.

**Comment by DavidGinzberg** [comment]
**Inconsistent indeed.**  
I just tested this on two Android (5.1.1) devices, a Nexus 5 phone and a Nexus 10 tablet, running the Chrome browser. On the tablet one tap on the navigation buttons caused the tooltip to appear, and a second tap on the same button causes the navigation behavior. On the phone there was no discernible response from tapping the navigation buttons.

Is anyone currently working on this? Looks like it's been nearly a month since this issue was posted so it could use an update.

**Comment by DavidGinzberg** [comment]
Further inspection reveals there's a span inside each button (for the icons) and the click events are on the spans, not the buttons. This is potentially causing the mobile issues and also causes the buttons not to respond if clicked inside the button but outside of the span (tested on Chrome 43.0.2357.124 m running on Windows 8.1)

**Comment by brianek** [comment]
So how to fix this? @jrleszcz @DavidGinzberg

**Comment by DavidGinzberg** [comment]
@brianek @jrleszcz I just submitted Pull Request #64. Should fix both issues discussed here. Ping me on slack if you have questions tomorrow.
