### ISSUE TITLE
What to do about Clean Slate/Rebuilding Re-entry Hackaton project

### ISSUE THREAD

**Issue by justgrimes** [codefordc/expungement-dc#6]
I'm depreciating the starter project that Code for DC worked on at the Rebuilding Re-entry Hackathon and directing people to come here instead; http://justgrimes.github.io/clean-slate

You might want to take some of the content...not much there but might be useful.

**Comment by mattbailey0** [comment]
Wait what? No don't do that.  We have a team working on this.

**Comment by justgrimes** [comment]
Sorry that might have been confusing. I am saying people are working on this project (what is here) and not the other one. I'm trying to redirect people to this project; and suggest you import some of the content from the other.

**Comment by mattbailey0** [comment]
OH. I completely misread the original message.  Sorry Justin!  We should definitely pull the extra content you and Shannon put together for the original project into this one.  We might even want to more fully merge them since the original is still out front of this one in terms of looking like a thing.

**Comment by rebeccawilliams** [comment]
I really like the Clean Slate name and home page general layout FWIW, also espanol!

**Comment by brianek** [comment]
Recommendation to close this issue.

**Comment by brianek** [comment]
any way I can get administrative privileges to close issues. Or do I already have that?
