### ISSUE TITLE
Allow for email feature. 

### ISSUE THREAD

**Issue by brianek** [codefordc/expungement-dc#62]
@cweems Would you happen to have some bandwith before thursday to see if the Email responses button is possible?

**Comment by DavidGinzberg** [comment]
I did a little digging on this. It looks like we could just use a `mailto:` URI and use some javascript to populate the body of the email with the user's answers. Mobile devices should pick up that URI and open the user's preferred email app. Desktop may need a little work since we can't guarantee they'll have an email client available (eg: users on public computers, or who use web-only email clients like gmail.com)

**Comment by meiao** [comment]
I had heard a while ago that you guys wanted to send emails from a app that has no backend.
Then I found about this tool:
http://www.mailthis.to/

Maybe it'll solve your problem.

**Comment by brianek** [comment]
Thank you!

**Comment by brianek** [comment]
@meiao We added a backend this weekend/or are adding backend so that might help things along.
