### ISSUE TITLE
Ineligible page instructions need a language update

### ISSUE THREAD

**Issue by DavidGinzberg** [codefordc/expungement-dc#65]
It looks like the names and/or appearances of the buttons have changed since the text for the ineligible page messages was written. As shown on [this page](http://codefordc.github.io/clean-slate/#/eligibility-check/q/legalAid) the text says `Please hit the "start over" button...` but that buttons seems to have been changed to an icon with a tooltip reading `Restart` instead. This may be confusing to some users, particularly if they are using a mobile device and can't see the tooltip.

Steps to fix:
1. Identify all pages using out of date wording in the navigation instructions (list them in comments here)
2. Update the pages with wording that is accurate to the current design of the site and easy to understand.

**Comment by brianek** [comment]
Thanks we can try to get someone on this tonight

**Comment by brianek** [comment]
@jrleszcz Would you want to work on this?

**Comment by ave-llan** [comment]
Yeah, I can work on this, though it could also be a good challenge for someone who wants to contribute without needing tech skills because you just have to edit the JSON. 

I was also thinking that many of these pages could be eliminated altogether by removing redundant questions.  For example, after selecting an option on this page, the question on the next page asks exactly the same thing:
![screen shot 2015-06-23 at 4 47 09 pm](https://cloud.githubusercontent.com/assets/7838603/8316828/8be67da2-19c7-11e5-9d3c-8248402359f8.png)

So if you click:
"arrested, charged or convicted of a marijuana-related offense before February 26, 2015" 

the next question is: 
"Were you arrested, charged or convicted of a marijuana-related offense before February 26, 2015?"

And then if you contradict your previous answer and say 'no' you get to the page @DavidGinzberg  is describing. 

Is there a reason we are asking twice or could the redundant questions just be removed?

**Comment by brianek** [comment]
@jrleszcz You right. Yes we can remove it. And yes we can have someone else (likely me) edit the JSON. Is there something else you want to work on? Or do you want me to wait until there is a big technical change? We are considering a web scraping project. Might you be interested in that? Also, @cweems is working on getting an "email" function that will sit right next to the "print" function. would you want to work with @cweems  on that?

**Comment by ave-llan** [comment]
PR #73 indirectly fixes this issue because the 'ineligible page' no longer exists.
